#!/usr/bin/env node
/**
 * Download the webfonts from Google once and serve them ourselves.
 *
 * Two reasons, and the second is what forced it:
 *  1. A third-party request on every page load is a poor look on a site whose
 *     argument is that the details are controlled.
 *  2. The CV PDF is rendered by a headless browser. Faces fetched over the
 *     network load lazily, so document.fonts.ready can resolve before they
 *     start, and the PDF came out in Times and Arial about half the time.
 *     Local files make it deterministic.
 *
 * Re-run to refresh: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

// Newsreader is requested as a WEIGHT RANGE, which makes Google serve one
// variable file instead of three statics: 129 KB once rather than per weight.
const SPEC =
  'family=Newsreader:opsz,wght@6..72,400..600' +
  '&family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;1,400' +
  '&family=IBM+Plex+Mono:wght@400;500';

// A modern UA makes Google serve woff2 rather than older formats.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

const OUT = resolve(process.cwd(), 'public/fonts');
await mkdir(OUT, { recursive: true });

const css = await (
  await fetch(`https://fonts.googleapis.com/css2?${SPEC}&display=swap`, {
    headers: { 'user-agent': UA },
  })
).text();

// Keep only the subsets the site actually needs. Spanish sits in latin-ext.
let out = '/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n';
let kept = 0;
let subset = null;

for (const line of css.split('\n')) {
  const comment = line.match(/^\/\*\s*([\w-]+)\s*\*\/$/);
  if (comment) {
    subset = comment[1];
    continue;
  }
  out += `${line}\n`;
}

// Pull each @font-face block, download its file, rewrite the url.
const blocks = [...out.matchAll(/@font-face\s*\{[^}]*\}/g)].map((m) => m[0]);
out = '/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n';

for (const block of blocks) {
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? '';
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
  const weight =
    block
      .match(/font-weight:\s*([\d\s]+);/)?.[1]
      ?.trim()
      .replace(/\s+/g, '-') ?? '400';
  const style = block.match(/font-style:\s*(\w+);/)?.[1] ?? 'normal';
  if (!url) continue;

  // Latin only. Google's latin subset spans U+0000-00FF, which covers every
  // accent the Spanish copy uses (a e i o u with acute, and n with tilde).
  // latin-ext is for Central and Eastern European and would roughly double
  // the payload for characters this site never renders.
  if (!range.includes('U+0000')) continue;

  const slug = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${style}.woff2`;
  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  await writeFile(resolve(OUT, slug), bytes);

  out += `${block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${slug}')`)}\n`;
  kept += 1;
  console.log(`  ${slug}  ${Math.round(bytes.length / 1024)} KB`);
}

await writeFile(resolve(process.cwd(), 'src/styles/fonts.css'), out);
console.log(`\n  ${kept} faces saved, src/styles/fonts.css written`);
